# Vehicle price prediction 
* the main aim of this project is to predict the efficiency of a vehicle based on the year of manufacture, mileage, fuel-type, km-driven, transmission type

In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Import the dataset

In [10]:
df = pd.read_csv(r"C:\Users\manit\OneDrive\Documents\GitHub\data_science_project\Car-details.csv")
df.sample(15) #sample method return the random sample data from the dataset

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats
1563,Jaguar XF 2.0 Diesel Portfolio,2017,3200000,45000,Diesel,Dealer,Automatic,First Owner,19.33 kmpl,1999 CC,177 bhp,430Nm@ 1750-2500rpm,5.0
5476,Mahindra Scorpio SLE BSIII,2013,600000,110000,Diesel,Individual,Manual,Second Owner,12.05 kmpl,2179 CC,120 bhp,290Nm@ 1800-2800rpm,8.0
838,Tata Sumo Gold EX BSIII,2017,400000,140000,Diesel,Individual,Manual,First Owner,14.07 kmpl,2956 CC,69.01 bhp,223Nm@ 1600-2200rpm,7.0
5324,Honda City i VTEC VX Option,2015,800000,50000,Petrol,Individual,Manual,First Owner,17.4 kmpl,1497 CC,117.3 bhp,145Nm@ 4600rpm,5.0
5603,Tata Nexon 1.2 Revotron XZ Plus,2018,850000,40000,Petrol,Individual,Manual,Second Owner,17.0 kmpl,1198 CC,108.5 bhp,170Nm@ 1750-4000rpm,5.0
3827,Hyundai Elantra SX,2013,511000,90000,Petrol,Individual,Manual,Second Owner,16.3 kmpl,1797 CC,147.5 bhp,177.5Nm@ 4700rpm,5.0
1265,Honda City 1.5 EXI,2002,81000,161000,Petrol,Individual,Manual,Fourth & Above Owner,13.0 kmpl,1493 CC,100 bhp,13.1kgm@ 4600rpm,5.0
524,Chevrolet Sail 1.2 LS ABS,2016,400000,30000,Petrol,Individual,Manual,First Owner,18.2 kmpl,1199 CC,82.4 bhp,108.5Nm@ 5000rpm,5.0
4855,Honda Amaze VX i-DTEC,2013,420000,40000,Diesel,Individual,Manual,Second Owner,25.8 kmpl,1498 CC,98.6 bhp,200Nm@ 1750rpm,5.0
7592,Tata Tiago 2019-2020 XZ Plus Dual Tone,2019,450000,3500,Petrol,Individual,Manual,First Owner,23.84 kmpl,1199 CC,83.83 bhp,114Nm@ 3500rpm,5.0
3477,Ford Figo 1.2P Titanium MT,2016,388000,50000,Petrol,Individual,Manual,Second Owner,18.16 kmpl,1196 CC,86.8 bhp,112Nm@ 4000rpm,5.0
3053,Maruti Swift Dzire VXI 1.2,2018,650000,15000,Petrol,Individual,Manual,First Owner,21.21 kmpl,1197 CC,81.80 bhp,113Nm@ 4200rpm,5.0
6617,Renault KWID 1.0 RXT Optional,2016,235000,60000,Petrol,Individual,Manual,First Owner,23.01 kmpl,999 CC,67 bhp,91Nm@ 4250rpm,5.0
7001,Maruti Alto 800 LXI,2013,185000,80000,Petrol,Individual,Manual,Second Owner,22.74 kmpl,796 CC,47.3 bhp,69Nm@ 3500rpm,5.0
829,Mahindra XUV500 W10 1.99 mHawk,2016,1165000,50000,Diesel,Individual,Manual,First Owner,16.0 kmpl,1997 CC,140 bhp,320Nm@ 1600-2800rpm,7.0

# Data Cleaning
* all the redundant and null valued data is removed

In [12]:
df.isnull().sum()

name               0
year               0
selling_price      0
km_driven          0
fuel               0
seller_type        0
transmission       0
owner              0
mileage          221
engine           221
max_power        215
torque           222
seats            221
dtype: int64

In [22]:
df = df.dropna()
df.isnull().sum()

name             0
year             0
selling_price    0
km_driven        0
fuel             0
seller_type      0
transmission     0
owner            0
mileage          0
engine           0
max_power        0
torque           0
seats            0
dtype: int64

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7906 entries, 0 to 8127
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           7906 non-null   object
 1   year           7906 non-null   int64
 2   selling_price  7906 non-null   int64
 3   km_driven      7906 non-null   int64
 4   fuel           7906 non-null   object
 5   seller_type    7906 non-null   object
 6   transmission   7906 non-null   object
 7   owner          7906 non-null   object
 8   mileage        7906 non-null   object
 9   engine         7906 non-null   object
 10  max_power      7906 non-null   object
 11  torque         7906 non-null   object
 12  seats          7906 non-null   float64
dtypes: float64(1), int64(3), object(9)
memory usage: 864.7+ KB

# Insights